apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
spec:
  template:
    spec:
      containers:
        - name: example-app
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
